build:
  binary: terraform-provider-circleci
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

dockers:
  -
    goos: linux
    goarch: amd64
    image: kasko/terraform-provider-circleci
