version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'
    working_directory: /go/src/github.com/kasko/terraform-provider-circleci
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run vet
          command: make vet

  release:
    executor:
      name: go/default
      tag: '1.17'
    working_directory: /go/src/github.com/kasko/terraform-provider-circleci
    steps:
      - checkout
      - run:
          name: Run goreleaser
          command: curl -sL https://git.io/goreleaser | bash
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - dist/

  dockerize:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: Build docker image
          command: docker build -t kasko/terraform-provider-circleci .
      - run:
          name: Tag & deploy docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag kasko/terraform-provider-circleci:latest kasko/terraform-provider-circleci:${CIRCLE_TAG}
            docker push kasko/terraform-provider-circleci:latest
            docker push kasko/terraform-provider-circleci:${CIRCLE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - dockerize:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
