---
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/kasko/terraform-provider-circleci
    steps:
      - checkout
      - run:
          name: Install go cookie
          command: bash scripts/gogetcookie.sh
      - run:
          name: Install govendor
          command: go get github.com/kardianos/govendor
      - run:
          name: Sync
          command: govendor sync
      - run:
          name: Run tests
          command: make test
      - run:
          name: Check vendor status
          command: make vendor-status
      - run:
          name: Run vet
          command: make vet

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/kasko/terraform-provider-circleci
    steps:
      - checkout
      - run:
          name: Run goreleaser
          command: curl -sL https://git.io/goreleaser | bash
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - dist/

  dockerize:
    docker:
      - image: docker:stable-git
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Build docker image
        command: docker build -t kasko/terraform-provider-circleci .
    - run:
        name: Tag & deploy docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push kasko/terraform-provider-circleci
          docker tag kasko/terraform-provider-circleci:${CIRCLE_TAG}
          docker push kasko/terraform-provider-circleci:${CIRCLE_TAG}



workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - dockerize:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
